### ISSUE TITLE
Roslynator.CSharp.Refactorings.AddUsingStaticDirectiveRefactoring.RefactorAsync - System.ArgumentException

### ISSUE THREAD

**Issue by nnpcYvIVl** [JosefPihrt/Roslynator#1148]
**Product and Version Used**: VS2022 and Roslynator 4.3.0

Visual studio displayed a yellow bar with the following stacktrace while typing in the IDE.

```
System.ArgumentException : usingKeyword
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.UsingDirective(SyntaxToken globalKeyword,SyntaxToken usingKeyword,SyntaxToken staticKeyword,SyntaxToken unsafeKeyword,NameEqualsSyntax alias,TypeSyntax namespaceOrType,SyntaxToken semicolonToken)
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.UsingDirective(SyntaxToken staticKeyword,NameEqualsSyntax alias,NameSyntax name)
   at async Roslynator.CSharp.Refactorings.AddUsingStaticDirectiveRefactoring.RefactorAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.PreviewChangesSuggestedAction.CreateAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.GetPreviewChangesFlavorAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.CreateAllFlavorsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

**Comment by JosefPihrt** [comment]
Fixed, please install latest version.

**Comment by nnpcYvIVl** [comment]
> Fixed, please install latest version.

Thanks!
