### ISSUE TITLE
Crash in FormatExpressionChainRefactoring

### ISSUE THREAD

**Issue by jnyrup** [JosefPihrt/Roslynator#120]
For this piece of code, if I
* Put the cursor inside the lambda expression, e.g. on `&&`
* Press `ctrl + .`
* Move the menu cursor to "Format binary expression on multiple lines" (if it's already not the first menu item)
* I get a top bar with "'DefaultCodeRefactoringProvider' encountered an error and has been disabled."

```csharp
var list = new object[] { };
            var properties = list
                .Where(p => p != null && p.GetHashCode() != 0);
```

The stacktrace:
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.GreenNode.AdjustFlagsAndWidth(GreenNode node)
   at Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxList.WithTwoChildren..ctor(GreenNode child0,GreenNode child1)
   at Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxList.List(GreenNode child0,GreenNode child1)
   at Microsoft.CodeAnalysis.Syntax.SyntaxTriviaListBuilder.ToList()
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.TriviaList(SyntaxTrivia[] trivias)
   at Roslynator.CSharp.CSharpFormatter.IncreaseIndentation(SyntaxTrivia trivia)
   at Roslynator.CSharp.CSharpFormatter.ToMultiLineAsync(Document document,MemberAccessExpressionSyntax[] expressions,CancellationToken cancellationToken)
   at Roslynator.CSharp.Refactorings.FormatExpressionChainRefactoring.<>c__DisplayClass0_1.<ComputeRefactoringsAsync>b__0(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.DocumentChangeAction.GetChangedDocumentAsync(CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

If I change it into this, it does not crash.
```csharp
var list = new object[] { };
            var properties = list.Where(p => p != null && p.GetHashCode() != 0);
```

I'm using version 1.4.51

**Comment by jnyrup** [comment]
Thanks!
