### ISSUE TITLE
Bug: UseMethodGroupInsteadOfAnonymousFunctionDiagnosticAnalyzer throws NullReferenceException

### ISSUE THREAD

**Issue by teoPL** [JosefPihrt/Roslynator#190]
`UseMethodGroupInsteadOfAnonymousFunctionDiagnosticAnalyzer` shows this message in the output window (Visual Studio 2017).

```
Severity	Code	Description	Project	File	Line	Suppression State	Tool	Detail Description
Warning	AD0001	Analyzer 'Roslynator.CSharp.DiagnosticAnalyzers.UseMethodGroupInsteadOfAnonymousFunctionDiagnosticAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	Project1		1	Active	Roslynator.CSharp.Analyzers	Analyzer 'Roslynator.CSharp.DiagnosticAnalyzers.UseMethodGroupInsteadOfAnonymousFunctionDiagnosticAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Project1
SyntaxTree: C:\Users\teo\documents\visual studio 2017\Projects\Project1\Project1\A.cs
SyntaxNode: delegate { Application.Exit(); } ... [AnonymousMethodExpressionSyntax]@[161..236) (8,44)-(11,13)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Roslynator.CSharp.Refactorings.UseMethodGroupInsteadOfAnonymousFunctionRefactoring.AnalyzeAnonyousMethodExpression(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__43`1.<ExecuteSyntaxNodeAction>b__43_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----'.
```

I was able to reproduce the problem using the following code:

```
using System.Windows.Forms;

namespace Project1
{
    class A : Form
    {
        void B()
        {
            this.BeginInvoke((MethodInvoker)delegate
            {
                Application.Exit();
            });
        }
    }
}
```

**Comment by JosefPihrt** [comment]
Thanks for the report @teoPL !

**Comment by aelij** [comment]
@JosefPihrt Hey, this started happening again in v1.8.0 during compilation:

CSC : error AD0001: Analyzer 'Roslynator.CSharp.DiagnosticAnalyzers.UseMethodGroupInsteadOfAnonymousFunctionDiagnosticAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.

**Comment by aelij** [comment]
Stack trace:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.FindConditionalAccessNodeForBinding(CSharpSyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Binder.GetReceiverForConditionalBinding(ExpressionSyntax binding, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindMemberBindingExpression(MemberBindingExpressionSyntax node, Boolean invoked, Boolean indexed, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodGroup(ExpressionSyntax node, Boolean invoked, Boolean indexed, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindInvocationExpression(InvocationExpressionSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSpeculativelyBoundExpressionHelper(Binder binder, ExpressionSyntax expression, SpeculativeBindingOption bindingOption, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSpeculativelyBoundExpression(Int32 position, ExpressionSyntax expression, SpeculativeBindingOption bindingOption, Binder& binder, ImmutableArray`1& crefSymbols)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSpeculativeSymbolInfo(Int32 position, ExpressionSyntax expression, SpeculativeBindingOption bindingOption)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSpeculativeSymbolInfoCore(Int32 position, SyntaxNode node, SpeculativeBindingOption bindingOption)
   at Roslynator.CSharp.Refactorings.UseMethodGroupInsteadOfAnonymousFunctionRefactoring.CheckSpeculativeSymbol(AnonymousFunctionExpressionSyntax anonymousFunction, ExpressionSyntax expression, IMethodSymbol methodSymbol, SemanticModel semanticModel, CancellationToken cancellationToken)
   at Roslynator.CSharp.Refactorings.UseMethodGroupInsteadOfAnonymousFunctionRefactoring.AnalyzeSimpleLambdaExpression(SyntaxNodeAnalysisContext context)
```

**Comment by JosefPihrt** [comment]
It seems that you are using package Roslynator.Analyzers 1.8.0.

Newer version 1.9.0-rc has been released and 1.9.0 will be released in a few days.

This bug could be fixed in the latest version but I'm not able to verify it without a repro. Could you provide a repro code?

**Comment by jnyrup** [comment]
I hit this today with Roslynator 1.9

Code
```csharp
private static IEnumerable<int> Transform<T>(BaseA<T> base, Func<T, int> prop)
    where T : BaseB, IItem<T> => base?.Items.Select(e => prop(e)).Distinct() ?? Enumerable.Empty<int>();
```

```
SyntaxNode: e => prop(e) [SimpleLambdaExpressionSyntax]@[8762..8774) (187,94)-(187,106)
```

Stack trace:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.FindConditionalAccessNodeForBinding(CSharpSyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Binder.GetReceiverForConditionalBinding(ExpressionSyntax binding, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindMemberBindingExpression(MemberBindingExpressionSyntax node, Boolean invoked, Boolean indexed, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindLeftOfPotentialColorColorMemberAccess(ExpressionSyntax left, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindMemberAccess(MemberAccessExpressionSyntax node, Boolean invoked, Boolean indexed, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodGroup(ExpressionSyntax node, Boolean invoked, Boolean indexed, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindInvocationExpression(InvocationExpressionSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSpeculativelyBoundExpressionHelper(Binder binder, ExpressionSyntax expression, SpeculativeBindingOption bindingOption, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSpeculativelyBoundExpression(Int32 position, ExpressionSyntax expression, SpeculativeBindingOption bindingOption, Binder& binder, ImmutableArray`1& crefSymbols)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSpeculativeSymbolInfo(Int32 position, ExpressionSyntax expression, SpeculativeBindingOption bindingOption)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSpeculativeSymbolInfoCore(Int32 position, SyntaxNode node, SpeculativeBindingOption bindingOption)
   at Roslynator.CSharp.Analysis.UseMethodGroupInsteadOfAnonymousFunctionAnalyzer.CheckSpeculativeSymbol(AnonymousFunctionExpressionSyntax anonymousFunction, ExpressionSyntax expression, IMethodSymbol methodSymbol, SemanticModel semanticModel, CancellationToken cancellationToken)
   at Roslynator.CSharp.Analysis.UseMethodGroupInsteadOfAnonymousFunctionAnalyzer.AnalyzeSimpleLambdaExpression(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__43`1.<ExecuteSyntaxNodeAction>b__43_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
```

**Comment by JosefPihrt** [comment]
moved to #390
