### ISSUE TITLE
'DefaultCodeRefactoringProvider' error during csx editing

### ISSUE THREAD

**Issue by teoPL** [JosefPihrt/Roslynator#274]
Visual studio show this error while editing `.csx` file:

![image](https://user-images.githubusercontent.com/33124857/36098905-05ff6c66-1001-11e8-9ff9-e558bc4a3b6d.png)
```
System.IndexOutOfRangeException : Index was outside the bounds of the array.
   at async Roslynator.CSharp.Refactorings.PromoteLocalToParameterRefactoring.ComputeRefactoringAsync(<Unknown Parameters>)
   at async Roslynator.CSharp.Refactorings.LocalDeclarationStatementRefactoring.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Roslynator.CSharp.Refactorings.RefactoringContext.ComputeRefactoringsForNodeAsync(<Unknown Parameters>)
   at async Roslynator.CSharp.Refactorings.RefactoringContext.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Roslynator.CSharp.Refactorings.DefaultCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
```

You can use this snippet to reproduce the problem:
```
#r "System.Net"

while (true)
{
    System.Net.WebClient client = new System.Net.WebClient();
    client.DownloadDataAsync(new System.Uri("http://localhost/"));
    client.DownloadDataCompleted += (sender, e) =>
    {
        System.Console.Write(System.DateTime.Now.Ticks + " ");
        System.Console.WriteLine(e.Error != null ? "ERR" : e.Result.Length.ToString());
        client.Dispose();
    };
    System.Threading.Thread.Sleep(10);
}
```

Thanks.

**Comment by nrandell** [comment]
Looks like this is already being handled, but also seeing this with the following stack trace

```
System.IndexOutOfRangeException : Index was outside the bounds of the array.
   at Roslynator.Utilities.StringUtility.ToCamelCase(String value,String prefix)
   at Roslynator.Utilities.StringUtility.ToCamelCase(String value,Boolean prefixWithUnderscore)
   at Roslynator.CSharp.Refactorings.InitializeFieldFromConstructorRefactoring.FieldInfo.Create(TypeSyntax type,VariableDeclaratorSyntax variableDeclarator)
   at Roslynator.CSharp.Refactorings.InitializeFieldFromConstructorRefactoring.ComputeRefactoring(RefactoringContext context,VariableDeclaratorSyntax variableDeclarator)
   at Roslynator.CSharp.Refactorings.VariableDeclaratorRefactoring.ComputeRefactorings(RefactoringContext context,VariableDeclaratorSyntax variableDeclarator)
   at async Roslynator.CSharp.Refactorings.RefactoringContext.ComputeRefactoringsForNodeAsync(<Unknown Parameters>)
   at async Roslynator.CSharp.Refactorings.RefactoringContext.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Roslynator.CSharp.Refactorings.DefaultCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
```

It was whilst typing in some code, so not sure exactly what caused it to happen.

It could have been
`private IReliableDictionary2<Guid, string> _deviceNameDictionary;`

or 

`_deviceNameDictionary = await StateManager.GetOrAddAsync<IReliableDictionary2<Guid, string>>($"names#{_partition}");`
