### ISSUE TITLE
ArgumentNullException at ToTypeSyntax

### ISSUE THREAD

**Issue by aelij** [JosefPihrt/Roslynator#303]
```
System.ArgumentNullException : Value cannot be null.
Parameter name: typeSymbol
   at Roslynator.CSharp.SymbolExtensions.ToTypeSyntax(ITypeSymbol typeSymbol,SymbolDisplayFormat format)
   at Roslynator.CSharp.Refactorings.InlineDefinition.InlineRefactoring`3.GetReplacementMap(SyntaxNode node,Dictionary`2 symbolMap)
   at Roslynator.CSharp.Refactorings.InlineDefinition.InlineRefactoring`3.RewriteNode[T](T node)
   at Roslynator.CSharp.Refactorings.InlineDefinition.InlineRefactoring`3.RewriteStatements(SyntaxList`1 statements)
   at Roslynator.CSharp.Refactorings.InlineDefinition.InlineRefactoring`3.InlineAsync(ExpressionStatementSyntax expressionStatement,SyntaxList`1 statements,CancellationToken cancellationToken)
   at Roslynator.CSharp.Refactorings.InlineDefinition.InlineAnalyzer`3.<>c__DisplayClass0_2.<ComputeRefactoringsAsync>b__2(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.DocumentChangeAction.GetChangedDocumentAsync(CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.PreviewChangesSuggestedAction.CreateAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.GetPreviewChangesFlavor(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.CreateAllFlavors(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

**Comment by aelij** [comment]
Unfortunately I don't have a repro.
Great job on Roslynator btw! :)

**Comment by JosefPihrt** [comment]
Thanks @aelij !
