### ISSUE TITLE
ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by tamlin-mike** [JosefPihrt/Roslynator#313]
Roslynator 1.8.0. VS 2017 15.6.3.

Not sure if this is really a bug in Roslynator, or if Microsoft's code. Perhaps both?

It triggered when hitting Alt+'.' and then using cursor down to move in the list of suggestions.

```
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
   at Microsoft.CodeAnalysis.SyntaxList`1.get_Item(Int32 index)
   at Roslynator.CSharp.Refactorings.SplitDeclarationAndInitializationRefactoring.RefactorAsync(Document document,SingleLocalDeclarationStatementInfo localInfo,TypeSyntax type,CancellationToken cancellationToken)
   at Roslynator.CSharp.Refactorings.SplitDeclarationAndInitializationRefactoring.<>c__DisplayClass0_0.<ComputeRefactoringAsync>b__0(CancellationToken f)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.DocumentChangeAction.GetChangedDocumentAsync(CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

**Comment by JosefPihrt** [comment]
Thanks for the report. This is probably a bug in Roslynator.

Would you be able to provide the code causes this bug?

**Comment by tamlin-mike** [comment]
I'm afraid the code that provoked this problem was so ugly and hairy it's since long gone and refactored. Luckily, it seems you identified and fixed the potential source. Thanks for looking into it.
