### ISSUE TITLE
ArgumentOutOfRangeException 

### ISSUE THREAD

**Issue by ppasieka** [JosefPihrt/Roslynator#459]
Roslynator
  Version: 2.0.0

I'm not sure how to reproduce this error. I was replacing some nuget package with different one, then some files started to report errors (because of missing stuff) and this exception happened.

```
System.ArgumentOutOfRangeException : startIndex must be less than length of string.
Parameter name: startIndex
   at System.String.Remove(Int32 startIndex)
   at Roslynator.StringUtility.GetLeadingWhitespaceExceptNewLine(String value)
   at Roslynator.CSharp.Refactorings.WrapSelectedLines.WrapSelectedLinesRefactoring.GetTextChanges(IEnumerable`1 selectedLines)
   at Roslynator.CSharp.Refactorings.SelectedLinesRefactoring.RefactorAsync(Document document,TextLineCollectionSelection selectedLines,CancellationToken cancellationToken)
   at Roslynator.CSharp.Refactorings.SelectedLinesRefactoring.<>c__DisplayClass2_0.<ComputeRefactoringsAsync>b__0(CancellationToken ct)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.DocumentChangeAction.GetChangedDocumentAsync(CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.PreviewChangesSuggestedAction.CreateAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.GetPreviewChangesFlavor(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.CreateAllFlavors(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

**Comment by JosefPihrt** [comment]
Thanks for the report @ppasieka !
