### ISSUE TITLE
Roslynator.CommandLine ArgumentException Reference of type 'Microsoft.CodeAnalysis.UnresolvedMetadataReference' is not valid

### ISSUE THREAD

**Issue by nnpcYvIVl** [JosefPihrt/Roslynator#491]
Using the following commandline:
```
Roslynator.exe analyze --ignore-compiler-diagnostics --use-roslynator-analyzers --ignore-analyzer-references "C:\Workspace\Solution.sln" --properties Configuration=Release
```

I get this crash:
```
Roslynator Command Line Tool version 0.1.0.1
Copyright (c) Josef Pihrt. All rights reserved.

Load solution 'C:\Workspace\Solution.sln'
Done loading solution 'C:\Workspace\Solution.sln'
Analyze solution 'C:\Workspace\Solution.sln'
Analyze 'Project1' 1/19
Analyze 'Project2' 2/19
Analyze 'Project3' 3/19
Analyze 'Project4' 4/19
Analyze 'Project5' 5/19
Analyze 'Project6' 6/19
Analyze 'Project7' 7/19
Analyze 'Project8' 8/19

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Reference of type 'Microsoft.CodeAnalysis.UnresolvedMetadataReference' is not valid for this compilation.
Parameter name: references[2]
   at Microsoft.CodeAnalysis.Compilation.ValidateReferences[T](IEnumerable`1 references)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.WithReferences(IEnumerable`1 references)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonWithReferences(IEnumerable`1 newReferences)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.UpdateCompilationWithNewReferencesAndRecordAssemblySymbols(Compilation compilation, List`1 newReferences, Dictionary`2 metadataReferenceToProjectId)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<FinalizeCompilationAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<BuildCompilationInfoFromScratchAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetOrBuildCompilationInfoAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetCompilationSlowAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Roslynator.Diagnostics.CodeAnalyzer.<AnalyzeProjectAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Roslynator.Diagnostics.CodeAnalyzer.<AnalyzeSolutionAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Roslynator.CommandLine.AnalyzeCommandExecutor.<ExecuteAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Roslynator.CommandLine.MSBuildWorkspaceCommandExecutor.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Roslynator.CommandLine.Program.<AnalyzeAsync>d__3.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Roslynator.CommandLine.Program.<>c.<Main>b__1_2(AnalyzeCommandLineOptions options)
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 parsedFunc6, Func`2 parsedFunc7, Func`2 parsedFunc8, Func`2 parsedFunc9, Func`2 parsedFunc10, Func`2 notParsedFunc)
   at Roslynator.CommandLine.Program.Main(String[] args)
```

**Comment by JosefPihrt** [comment]
This seems to be a bug in Roslyn.

Is that solution buildable in VS?
Can you give me a link to that solution?

**Comment by JosefPihrt** [comment]
ping @nnpcYvIVl

**Comment by nnpcYvIVl** [comment]
@JosefPihrt The solution builds in VS. I can't share this solution but will try to make a small repro.

**Comment by nnpcYvIVl** [comment]
@JosefPihrt I've attached a repro with a batch file. To trigger the bug make sure bin and obj folders don't exist when running Roslynator. The included batch file deletes these folders if they exist.

[Roslynator ArgumentException UnresolvedMetadataReference.zip](https://github.com/JosefPihrt/Roslynator/files/2818638/Roslynator.ArgumentException.UnresolvedMetadataReference.zip)

**Comment by JosefPihrt** [comment]
I found it. This bug is being tracked here: https://github.com/dotnet/roslyn/issues/30174

Workaround is to set property `ShouldUnsetParentConfigurationAndPlatform` to `false`

I checked latest version **Microsoft.CodeAnalysis.Workspaces.MSBuild.3.0.0-beta2-final** and the bug has been fixed.

**Comment by nnpcYvIVl** [comment]
@JosefPihrt I tried using the ```ShouldUnsetParentConfigurationAndPlatform``` like you suggested but I am still getting the error.

```
Roslynator.exe analyze --ignore-compiler-diagnostics --use-roslynator-analyzers --ignore-analyzer-references ".\Solution1\Solution1.sln" --properties "Platform=Any CPU" "Configuration=Release" "ShouldUnsetParentConfigurationAndPlatform=false" -v d   & PAUSE
Roslynator Command Line Tool version 0.1.0.1
Copyright (c) Josef Pihrt. All rights reserved.

Add MSBuild property Platform                                  = Any CPU
Add MSBuild property Configuration                             = Release
Add MSBuild property ShouldUnsetParentConfigurationAndPlatform = false
Load solution '.\Solution1\Solution1.sln'
  Resolve   00:00.00  Solution2.csproj
  Resolve   00:00.17  Solution1.csproj
Done loading solution 'C:\Workspace\Roslynator ArgumentException UnresolvedMetadataReference\Solution1\Solution1.sln'
Add analyzer assembly 'Roslynator.CSharp.Analyzers, Version=2.0.1.0, Culture=neutral, PublicKeyToken=819946f740867a8a'
Analyze solution 'C:\Workspace\Roslynator ArgumentException UnresolvedMetadataReference\Solution1\Solution1.sln'
Analyze 'Solution1' 1/2

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Reference of type 'Microsoft.CodeAnalysis.UnresolvedMetadataReference' is not valid for this compilation.
```

Am I doing something wrong?

**Comment by JosefPihrt** [comment]
Hmm, it seems that workaround does not work when `Platform` is set to `Any CPU`.

However, the error does not occur if I use latest library **Microsoft.CodeAnalysis.Workspaces.MSBuild.3.0.0-beta2-final**.

So the resolution is:
* this is external issue that I cannot fix.
* It should not occur in future releases of CLI which will use **Microsoft.CodeAnalysis.Workspaces.MSBuild.3.***

**Comment by nnpcYvIVl** [comment]
@JosefPihrt Thanks, I tried using MSBuild 3 and it works great!
