### ISSUE TITLE
NullReferenceException in UseMethodGroupInsteadOfAnonymousFunctionAnalyzer

### ISSUE THREAD

**Issue by jnyrup** [JosefPihrt/Roslynator#548]
**Product and Version Used**: 
Visual Studio 16.0.3
Roslynator 2019 [Preview] version 2.1.0

**Steps to Reproduce**:
```c#
void Foo()
{
    new List<object>().Select(node => Bar(node))?.ToList();
}

public object Bar(object node)
{
    return new object();
}
```

When inserting a `?` after the `List`, i.e. `List<object>()?.Select` the analyzer immediately crashes.

**Stack Trace**:
```
'Roslynator.CSharp.Analysis.UseMethodGroupInsteadOfAnonymousFunctionAnalyzer' threw an exception of type 'System.NullReferenceException' 
with message 'Object reference not set to an instance of an object.'.	ConsoleApp113		1	Active	Analyzer 'Roslynator.CSharp.Analysis.UseMethodGroupInsteadOfAnonymousFunctionAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: ConsoleApp113
SyntaxTree: C:\Users\jonas\source\repos\ConsoleApp113\ConsoleApp113\Program.cs
SyntaxNode: node => Bar(node) [SimpleLambdaExpressionSyntax]@[248..265) (14,39)-(14,56)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.FindConditionalAccessNodeForBinding(CSharpSyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Binder.GetReceiverForConditionalBinding(ExpressionSyntax binding, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindMemberBindingExpression(MemberBindingExpressionSyntax node, Boolean invoked, Boolean indexed, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodGroup(ExpressionSyntax node, Boolean invoked, Boolean indexed, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindInvocationExpression(InvocationExpressionSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSpeculativelyBoundExpressionHelper(Binder binder, ExpressionSyntax expression, SpeculativeBindingOption bindingOption, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSpeculativelyBoundExpression(Int32 position, ExpressionSyntax expression, SpeculativeBindingOption bindingOption, Binder& binder, ImmutableArray`1& crefSymbols)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSpeculativeSymbolInfo(Int32 position, ExpressionSyntax expression, SpeculativeBindingOption bindingOption)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSpeculativeSymbolInfoCore(Int32 position, SyntaxNode node, SpeculativeBindingOption bindingOption)
   at Roslynator.CSharp.Analysis.UseMethodGroupInsteadOfAnonymousFunctionAnalyzer.CheckSpeculativeSymbol(AnonymousFunctionExpressionSyntax anonymousFunction, ExpressionSyntax expression, IMethodSymbol methodSymbol, SemanticModel semanticModel, CancellationToken cancellationToken)
   at Roslynator.CSharp.Analysis.UseMethodGroupInsteadOfAnonymousFunctionAnalyzer.AnalyzeSimpleLambdaExpression(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__50`1.<ExecuteSyntaxNodeAction>b__50_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
```

**Comment by jnyrup** [comment]
As always, thanks for the continued improvements of this great tool

**Comment by JosefPihrt** [comment]
I thank you for reporting all these bugs!
