### ISSUE TITLE
MissingMethodException using commandline.0.1.0-rec

### ISSUE THREAD

**Issue by FolkCoder** [JosefPihrt/Roslynator#577]
I am unable to run the console tool on my project using the  commandline.0.1.0-rc nuget package, receiving the following error (truncated):

```
Fix 5 RCS1103 'Replace if statement with assignment.'

System.AggregateException: One or more errors occurred. ---> System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Microsoft.CodeAnalysis.Document> Roslynator.CSharp.Refactorings.IfRefactoring.RefactorAsync(Microsoft.CodeAnalysis.Document, Roslynator.CSharp.Analysis.If.IfAnalysis, System.Threading.CancellationToken)'.
   at Roslynator.CSharp.CodeFixes.IfStatementCodeFixProvider.<>c__DisplayClass2_2.<RegisterCodeFixesAsync>b__1(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.DocumentChangeAction.GetChangedDocumentAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.<GetChangedSolutionAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.<GetChangedSolutionInternalAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.<GetChangedDocumentsAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.<GetDocumentIdToChangedDocuments>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.<TryMergeFixesAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.<TryGetMergedFixAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.<GetFixAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.<GetFixAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Roslynator.CodeFixes.DiagnosticFixProvider.<GetFixAsync>d__1.MoveNext() in C:\Users\username\files\repos\Roslynator\src\Workspaces.Core\CodeFixes\DiagnosticFixProvider.cs:line 140
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Roslynator.CodeFixes.DiagnosticFixProvider.<GetFixAsync>d__0.MoveNext() in C:\Users\username\files\repos\Roslynator\src\Workspaces.Core\CodeFixes\DiagnosticFixProvider.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Roslynator.CodeFixes.CodeFixer.<FixDiagnosticsAsync>d__18.MoveNext() in C:\Users\username\files\repos\Roslynator\src\Workspaces.Core\CodeFixes\CodeFixer.cs:line 428
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Roslynator.CodeFixes.CodeFixer.<FixDiagnosticsAsync>d__17.MoveNext() in C:\Users\username\files\repos\Roslynator\src\Workspaces.Core\CodeFixes\CodeFixer.cs:line 405
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Roslynator.CodeFixes.CodeFixer.<FixProjectAsync>d__16.MoveNext() in C:\Users\username\files\repos\Roslynator\src\Workspaces.Core\CodeFixes\CodeFixer.cs:line 264
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Roslynator.CodeFixes.CodeFixer.<FixProjectAsync>d__15.MoveNext() in C:\Users\username\files\repos\Roslynator\src\Workspaces.Core\CodeFixes\CodeFixer.cs:line 125
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Roslynator.CodeFixes.CodeFixer.<FixSolutionAsync>d__14.MoveNext() in C:\Users\username\files\repos\Roslynator\src\Workspaces.Core\CodeFixes\CodeFixer.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Roslynator.CommandLine.FixCommand.<FixAsync>d__14.MoveNext() in C:\Users\username\files\repos\Roslynator\src\CommandLine\Commands\FixCommand.cs:line 100
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Roslynator.CommandLine.FixCommand.<ExecuteAsync>d__13.MoveNext() in C:\Users\username\files\repos\Roslynator\src\CommandLine\Commands\FixCommand.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Roslynator.CommandLine.MSBuildWorkspaceCommand.<ExecuteAsync>d__7.MoveNext() in C:\Users\username\files\repos\Roslynator\src\CommandLine\Commands\MSBuildWorkspaceCommand.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Roslynator.CommandLine.Program.<FixAsync>d__1.MoveNext() in C:\Users\username\files\repos\Roslynator\src\CommandLine\Program.cs:line 140
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Roslynator.CommandLine.Program.<>c.<Main>b__0_6(FixCommandLineOptions options) in C:\Users\username\files\repos\Roslynator\src\CommandLine\Program.cs:line 92
   at Roslynator.CommandLine.Program.Main(String[] args) in C:\Users\username\files\repos\Roslynator\src\CommandLine\Program.cs:line 84
---> (Inner Exception #0) System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Microsoft.CodeAnalysis.Document> Roslynator.CSharp.Refactorings.IfRefactoring.RefactorAsync(Microsoft.CodeAnalysis.Document, Roslynator.CSharp.Analysis.If.IfAnalysis, System.Threading.CancellationToken)'.
   at Roslynator.CSharp.CodeFixes.IfStatementCodeFixProvider.<>c__DisplayClass2_2.<RegisterCodeFixesAsync>b__1(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.DocumentChangeAction.GetChangedDocumentAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.<GetChangedSolutionAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.<GetChangedSolutionInternalAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.<GetChangedDocumentsAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.<GetDocumentIdToChangedDocuments>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.<TryMergeFixesAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.<TryGetMergedFixAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.<GetFixAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeFixes.BatchFixAllProvider.<GetFixAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Roslynator.CodeFixes.DiagnosticFixProvider.<GetFixAsync>d__1.MoveNext() in C:\Users\username\files\repos\Roslynator\src\Workspaces.Core\CodeFixes\DiagnosticFixProvider.cs:line 140
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Roslynator.CodeFixes.DiagnosticFixProvider.<GetFixAsync>d__0.MoveNext() in C:\Users\username\files\repos\Roslynator\src\Workspaces.Core\CodeFixes\DiagnosticFixProvider.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Roslynator.CodeFixes.CodeFixer.<FixDiagnosticsAsync>d__18.MoveNext() in C:\Users\username\files\repos\Roslynator\src\Workspaces.Core\CodeFixes\CodeFixer.cs:line 428
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Roslynator.CodeFixes.CodeFixer.<FixDiagnosticsAsync>d__17.MoveNext() in C:\Users\username\files\repos\Roslynator\src\Workspaces.Core\CodeFixes\CodeFixer.cs:line 405
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Roslynator.CodeFixes.CodeFixer.<FixProjectAsync>d__16.MoveNext() in C:\Users\username\files\repos\Roslynator\src\Workspaces.Core\CodeFixes\CodeFixer.cs:line 264
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Roslynator.CodeFixes.CodeFixer.<FixProjectAsync>d__15.MoveNext() in C:\Users\username\files\repos\Roslynator\src\Workspaces.Core\CodeFixes\CodeFixer.cs:line 125
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Roslynator.CodeFixes.CodeFixer.<FixSolutionAsync>d__14.MoveNext() in C:\Users\username\files\repos\Roslynator\src\Workspaces.Core\CodeFixes\CodeFixer.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Roslynator.CommandLine.FixCommand.<FixAsync>d__14.MoveNext() in C:\Users\username\files\repos\Roslynator\src\CommandLine\Commands\FixCommand.cs:line 100
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Roslynator.CommandLine.FixCommand.<ExecuteAsync>d__13.MoveNext() in C:\Users\username\files\repos\Roslynator\src\CommandLine\Commands\FixCommand.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Roslynator.CommandLine.MSBuildWorkspaceCommand.<ExecuteAsync>d__7.MoveNext() in C:\Users\username\files\repos\Roslynator\src\CommandLine\Commands\MSBuildWorkspaceCommand.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Roslynator.CommandLine.Program.<FixAsync>d__1.MoveNext()
```

I thought this might be related https://github.com/JosefPihrt/Roslynator/issues/491, but updating the associated Microsoft.CodeAnalysis references to v3.3.0-beta1-final in the CommandLine solution did not fix the issue.

The command I used:

```
C:\Users\username\Desktop\roslynator\Roslynator.CommandLine.0.1.0-rc2\tools\net472\roslynator.exe fix "C:\Users\username\files\repos\solution\WebSolution.sln" --analyzer-assemblies "C:\Users\username\Desktop\roslynator\Roslynator.Analyzers.2.1.0\analyzers\dotnet\cs" --file-log="C:\Users\username\Desktop\roslynator\roslynator-log.txt" --file-log-verbosity=diagnostic --ignore-analyzer-references --ignore-compiler-errors --msbuild-path="C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin" --projects="TestProject" --properties CodeAnalysisRuleset="C:\Users\username\Desktop\roslynator\roslynator.ruleset" Platform="x86" --severity-level=info --verbosity=normal
```

The same command works fine with commandline.0.1.0-rc. I cannot reproduce the issue in a new empty project, so it may be something particular to my configuration, but posting it in case anyone has an idea or two.

Thanks for your help!

**Comment by JosefPihrt** [comment]
Hi,

Thanks for the report. I was able to reproduce this bug.

Problem seems to lie in the fact that both folders

`roslynator.analyzers.2.1.0\analyzers\dotnet\cs`
`roslynator.commandline.0.1.0-rc2\tools\net472`

contain exactly the same common libraries (Roslynator.Core and others).

### Workaround

Reference analyzer assemblies that are contained in the CLI folder:

change`--analyzer-assemblies "C:\Users\username\Desktop\roslynator\Roslynator.Analyzers.2.1.0\analyzers\dotnet\cs"`

to `--analyzer-assemblies "C:\Users\username\Desktop\roslynator\Roslynator.CommandLine.0.1.0-rc2\tools\net472"`

### Solution

In the next release of CLI I will use different versioning for the common libraries.

**Comment by FolkCoder** [comment]
This seems to be working. Thanks for the workaround!
