### ISSUE TITLE
Analyzer 'Roslynator.CSharp.Analysis.CallExtensionMethodAsInstanceMethodAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'This program location is thought to be unreachable.'.

### ISSUE THREAD

**Issue by CheloXL** [JosefPihrt/Roslynator#633]
**Product and Version Used**: 
Roslynator 2.3.0
VS 2019

**Steps to Reproduce**:
Below is the code that Roslynator shows as problematic.
Full error is:
```
Roslynator.CSharp.Analysis.CallExtensionMethodAsInstanceMethodAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'This program location is thought to be unreachable.'.	Extensions		1	Active	Analyzer 'Roslynator.CSharp.Analysis.CallExtensionMethodAsInstanceMethodAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: DDS.Runtime.Extensions
SyntaxTree: D:\2DS\CoreDotNet\Extensions\Extensions\IEnumerableExtensions.cs
SyntaxNode: TryCount(source, out var count) ... [InvocationExpressionSyntax]@[5565..5596) (182,7)-(182,38)

System.InvalidOperationException: This program location is thought to be unreachable.
   at Microsoft.CodeAnalysis.CSharp.Binder.BindOutVariableDeclarationArgument(DeclarationExpressionSyntax declarationExpression, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindOutDeclarationArgument(DeclarationExpressionSyntax declarationExpression, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentValue(DiagnosticBag diagnostics, ArgumentSyntax argumentSyntax, Boolean allowArglist, RefKind refKind)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentAndName(AnalyzedArguments result, DiagnosticBag diagnostics, Boolean& hadError, Boolean& hadLangVersionError, ArgumentSyntax argumentSyntax, Boolean allowArglist, Boolean isDelegateCreation)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindInvocationExpression(InvocationExpressionSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSpeculativelyBoundExpression(Int32 position, ExpressionSyntax expression, SpeculativeBindingOption bindingOption, Binder& binder, ImmutableArray`1& crefSymbols)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSpeculativelyBoundExpression(Int32 position, ExpressionSyntax expression, SpeculativeBindingOption bindingOption, Binder& binder, ImmutableArray`1& crefSymbols)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSpeculativeSymbolInfo(Int32 position, ExpressionSyntax expression, SpeculativeBindingOption bindingOption)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSpeculativeSymbolInfoCore(Int32 position, SyntaxNode node, SpeculativeBindingOption bindingOption)
   at Roslynator.SemanticModelExtensions.GetSpeculativeMethodSymbol(SemanticModel semanticModel, Int32 position, SyntaxNode expression)
   at Roslynator.CSharp.Analysis.CallExtensionMethodAsInstanceMethodAnalysis.Analyze(InvocationExpressionSyntax invocationExpression, SemanticModel semanticModel, Boolean allowAnyExpression, CancellationToken cancellationToken)
   at Roslynator.CSharp.Analysis.CallExtensionMethodAsInstanceMethodAnalyzer.AnalyzeInvocationExpression(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__55`1.<ExecuteSyntaxNodeAction>b__55_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
```

**Code**:
```csharp
public static class EnumerableExtensions {
	public static bool TryCount<T>(this IEnumerable<T>? source, out int count)
	{
		switch (source) {
			case null:
				count = 0;
				return false;

			case ICollection<T> collection1:
				count = collection1.Count;
				return true;

			case ICollection collection2:
				count = collection2.Count;
				return true;
		}

		count = 0;
		return false;
	}
}
```

**Comment by JosefPihrt** [comment]
The error occurs at the location where the method is invoked not defined. Could you please provide a code where the method 'TryCount' is invoked? The location is 5565 which is number of characters from the start of the document.

**Comment by CheloXL** [comment]
I believe is in the following piece of code...
```csharp
public static bool IsNullOrEmpty<T>(this IEnumerable<T>? source)
{
	if (source == null)
	{
		return true;
	}

	if (TryCount(source, out var count))
	{
		return count == 0;
	}

	return !source.GetEnumerator().MoveNext();
}
```

**Comment by JosefPihrt** [comment]
Thanks. I'm able to reproduce this bug.

It seems to be a bug in Roslyn.

**Comment by JosefPihrt** [comment]
I filed an issue in Roslyn repo: https://github.com/dotnet/roslyn/issues/41355
