### ISSUE TITLE
RR0062: Inline method throws ArgumentException

### ISSUE THREAD

**Issue by Buthrakaur** [JosefPihrt/Roslynator#73]
I tried to inline method, which is used from multiple places, but Roslynator throws exception:

```
System.ArgumentException : Syntax node is not within syntax tree
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.CheckSyntaxNode(CSharpSyntaxNode syntax)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetSymbolInfo(SemanticModel semanticModel,ExpressionSyntax expression,CancellationToken cancellationToken)
   at Roslynator.CSharp.Refactorings.InlineMethod.InlineMethodRefactoring.RewriteNode[TNode](TNode node,IMethodSymbol methodSymbol,ParameterInfo[] parameterInfos,SemanticModel semanticModel,CancellationToken cancellationToken)
   at Roslynator.CSharp.Refactorings.InlineMethod.InlineMethodRefactoring.RewriteExpression(ExpressionSyntax expression,IMethodSymbol methodSymbol,ParameterInfo[] parameterInfos,SemanticModel semanticModel,CancellationToken cancellationToken)
   at Roslynator.CSharp.Refactorings.InlineMethod.InlineMethodRefactoring.<>c__DisplayClass0_4.<ComputeRefactoringsAsync>b__1(CancellationToken c)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.DocumentChangeAction.GetChangedDocumentAsync(CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

**Comment by JosefPihrt** [comment]
Thanks for the report @Buthrakaur !
