### ISSUE TITLE
RCS1077: Analyzer `Roslynator.CSharp.Analysis.InvocationExpressionAnalyzer` threw an exception of type `System.ArgumentNullException`

### ISSUE THREAD

**Issue by JoshuaLight** [JosefPihrt/Roslynator#732]
**Product and Version Used**: `Roslynator.Analyzers v3.0.0`.
**Problem**: Have the following exception when analyzing the project:
```
Analyzer 'Roslynator.CSharp.Analysis.InvocationExpressionAnalyzer' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null.
```
**Question**: The problem is probably in some specific code. How can I debug the analyzer to find what the exact line that is causing the exception?

_Note: turning off `RCS1077` fixes the exception._

**Comment by JosefPihrt** [comment]
I don't know which IDE do you use but in Visual Studio you can click on the item in the error list to see more information

https://user-images.githubusercontent.com/2000163/59884939-b058fa00-9387-11e9-910c-1cdac9ef339f.png

**Comment by JoshuaLight** [comment]
I'm using Rider. Thanks, will try to find more info about the error in Rider or at least will try to open the project with Visual Studio. BRB with details.

**Comment by JoshuaLight** [comment]
Sorry for being too slow.

Anyway, I've found that the exception is thrown for the following kind of statement:
```cs
_ = A()
  .SelectMany(B())
  .Count();

Func<T, IEnumerable<T>> B() => ...;
```

Seems like the problem is with calling a function `B()` that returns a `selector` for `SelectMany`.

The full stack trace:
```
CSC error AD0001: Analyzer 'Roslynator.CSharp.Analysis.InvocationExpressionAnalyzer' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null.
Parameter name: syntax
at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.CheckSyntaxNode(CSharpSyntaxNode syntax)
at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetTypeInfo(ExpressionSyntax expression, CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetTypeInfo(SemanticModel semanticModel, ExpressionSyntax expression, CancellationToken cancellationToken)
at Roslynator.CSharp.Analysis.OptimizeLinqMethodCallAnalysis.AnalyzeSelectManyAndCount(SyntaxNodeAnalysisContext context, SimpleMemberInvocationExpressionInfo& invocationInfo)
at Roslynator.CSharp.Analysis.InvocationExpressionAnalyzer.AnalyzeInvocationExpression(SyntaxNodeAnalysisContext context)
at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__58`1.<ExecuteSyntaxNodeAction>b__58_0(ValueTuple`2 data)
at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
```

**Comment by JosefPihrt** [comment]
Thanks for the report. I'm able to reproduce this bug.
