### ISSUE TITLE
JoinStringExpressionsRefactoring is broken when selection extends to margin

### ISSUE THREAD

**Issue by IanKemp** [JosefPihrt/Roslynator#767]
**Product and Version Used**: VS 2019 Enterprise 16.8.4 / Roslynator 2019 3.1.0

**Steps to Reproduce**:

Select a string that's been broken into multiple lines and press `Ctrl + .` (or whatever the "show refactorings" shortcut is in your VS install). **Depending on the string and how it has been selected**, the refactoring will either work or throw an exception.

The following works - note that the selection extends from *before the first quote in the first line* to the end of the last quote on the third line:

![image](https://user-images.githubusercontent.com/1726434/105885278-d97c4a80-6000-11eb-99cf-79ecce03d229.png)

The following (*using the exact same string*) **fails** - note that the selection extends *from the left margin* to the end of the last quote on the third line:

![image](https://user-images.githubusercontent.com/1726434/105885592-3d067800-6001-11eb-8921-255433f87ea0.png)

Performing the same "show refactorings" command after the exception is thrown, yields a menu with blank items:

![image](https://user-images.githubusercontent.com/1726434/105885361-f3b62880-6000-11eb-9673-196841e6fea1.png)

The stack trace:

```
System.ArgumentOutOfRangeException : StartIndex cannot be less than zero.
Parameter name: startIndex
   at System.String.Remove(Int32 startIndex)
   at Roslynator.CSharp.Refactorings.JoinStringExpressionsRefactoring.RefactorAsync(Document document,StringConcatenationExpressionInfo& concatenationInfo,ExpressionSyntax expression,CancellationToken cancellationToken)
   at Roslynator.CSharp.Refactorings.JoinStringExpressionsRefactoring.<>c__DisplayClass0_0.<ComputeRefactoring>b__1(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.DocumentChangeAction.GetChangedDocumentAsync(CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

**Comment by IanKemp** [comment]
As always Josef, thank you for all your hard and continuous work on this incredibly useful extension.

**Comment by JosefPihrt** [comment]
I thank you for making regular donation. If it would be possible I would make you platinum member of something like that 🥇 🙂.
