### ISSUE TITLE
InvalidCastException on getting suggestion(s)

### ISSUE THREAD

**Issue by tamlin-mike** [JosefPihrt/Roslynator#871]
**Product and Version Used**: Roslynator 3.3.0 on VS 16.11.5.

**Steps to Reproduce**: Hitting Alt+Return on an expression in VS.

**Actual Behavior**:
```csharp
using System.Runtime.CompilerServices;
namespace NS {
class C {
  private static bool foo(Type type)
  {
    return type.HasAttribute<CompilerGeneratedAttribute>() || type.IsNotPublic;
  }
}
```

InvalidCastException with cursor "touching" anything in `HasAttribute<CompilerGeneratedAttribute>` and hitting Alt+Return. Strangely enough does not fail if the attribute is spelled out with its FQN, or if using any (?) other attribute. That makes me wonder if this is even a Roslynator bug, or if this is a Microsoft issue. Starting here, though, due to honorable mention in call stack. :-)

<details>
<summary>Stack trace</summary>
```
System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.ParenthesizedExpressionSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.TypeSyntax'.
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitTypeOfExpression(TypeOfExpressionSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.TypeOfExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitArgument(ArgumentSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SeparatedSyntaxList`1 list)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitArgumentList(ArgumentListSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentListSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitInvocationExpression(InvocationExpressionSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InvocationExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Roslynator.CSharp.Refactorings.InlineDefinition.InlineRefactoring`3.RewriteNode[T](T node)
   at Roslynator.CSharp.Refactorings.InlineDefinition.InlineRefactoring`3.RewriteExpression(SyntaxNode node,ExpressionSyntax expression)
   at Roslynator.CSharp.Refactorings.InlineDefinition.InlineRefactoring`3.InlineAsync(SyntaxNode node,ExpressionSyntax expression,CancellationToken cancellationToken)
   at Roslynator.CSharp.Refactorings.InlineDefinition.InlineAnalyzer`3.<>c__DisplayClass0_0.<ComputeRefactoringsAsync>b__1(CancellationToken ct)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.DocumentChangeAction.GetChangedDocumentAsync(CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```
</details>

**Comment by JosefPihrt** [comment]
Thanks for the report.

This is probably bug in Roslynator. To fix this bug I need the source code of the extension method `HasAttribute<CompilerGeneratedAttribute>`. Can you please provide it?

**Comment by tamlin-mike** [comment]
```csharp
public static bool HasAttribute<T>(this MemberInfo mi) where T : Attribute
{
  return Attribute.IsDefined(mi, typeof(T));
}
```

**Comment by JosefPihrt** [comment]
Thanks.

I was not able to reproduce the bug. Nevertheless I found similar issue #568.

I assume that that there was done some improvement in Roslyn that prevents this bug from occur on my machine. But I made the fix anyway.
