### ISSUE TITLE
warning AD0001: Analyzer 'Roslynator.CSharp.Analysis.InvocationExpressionAnalyzer' threw an exception of type 'System.NullReferenceException'

### ISSUE THREAD

**Issue by baal2000** [JosefPihrt/Roslynator#937]
**Product and Version Used**: 
[Roslynator.CSharp.Analysis](https://www.nuget.org/packages/Roslynator.Analyzers) 

Released versions:  4.1.1 and earlier

**Actual Behavior**:
A conditional operator similar to:
```csharp
   boolean_value ? "ab" : 'c'
```
where "ab" is  a `string` value and 'c' is `a char` value causes
```csharp
warning AD0001: Analyzer 'Roslynator.CSharp.Analysis.InvocationExpressionAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. 
```

**Expected Behavior**:
```csharp
error RCS1198: Avoid unnecessary boxing of value type. 
```

**Steps to Reproduce**:
Try this case-specific repro: https://github.com/baal2000/RoslynatorAnalyzerNRE
![image](https://user-images.githubusercontent.com/22180333/183911935-841df926-b884-4dc9-a02b-c658648af50a.png)

**Comment by baal2000** [comment]
This could be helpful to others who need to troubleshoot other AD0001 warnings. 

I could not find if there is a simple cross-platform Roslyn analyzer error logging that a user can take and bring to the developer or to simplify the issue reproduction without having to setup a dev [environment](https://msdn.microsoft.com/magazine/dn879356.aspx).

I realize this maybe still too steep of a learning curve due to some low-level coding effort involved into the troubleshooting. Please comment if there is a simpler technique. 
 
So I placed
```
try
{
        [   InvocationExpressionAnalyzer.AnalyzeInvocationExpression body ]
}
catch (NullReferenceException ex)
{
      Debug.Fail($"{ex.Message}{Environment.NewLine}{ex.StackTrace}");
}
``` 
into the particular analyzer mentioned in AD0001 warning. Then compiled in debug and replaced the stock version of the analyzer dll with the custom along with the pdb file. 

Running **dotnet build** gave 
```
/usr/share/dotnet/sdk/6.0.302/Roslyn/Microsoft.CSharp.Core.targets(75,5): error : Process terminated. Assertion failed. [/home/sergepavlov/Repro/RoslynatorAnalyzerNRE/RoslynatorAnalyzerNRE.csproj]
  Microsoft.CSharp.Core.targets(75, 5): Object reference not set to an instance of an object.
  Microsoft.CSharp.Core.targets(75, 5):    at Roslynator.CSharp.Analysis.AvoidBoxingOfValueTypeAnalysis.Analyze(SyntaxNodeAnalysisContext context, SimpleMemberInvocationExpressionInfo& invocationInfo) in /home/sergepavlov/Repro/Analyzers/CSharp/Analysis/AvoidBoxingOfValueTypeAnalysis.cs:line 41
  Microsoft.CSharp.Core.targets(75, 5):    at Roslynator.CSharp.Analysis.InvocationExpressionAnalyzer.AnalyzeInvocationExpression(SyntaxNodeAnalysisContext context) in /home/sergepavlov/Repro/Analyzers/CSharp/Analysis/InvocationExpressionAnalyzer.cs:line 450
  Microsoft.CSharp.Core.targets(75, 5):    at Roslynator.CSharp.Analysis.InvocationExpressionAnalyzer.AnalyzeInvocationExpression(SyntaxNodeAnalysisContext context) in /home/sergepavlov/Repro/Analyzers/CSharp/Analysis/InvocationExpressionAnalyzer.cs:line 450
  Microsoft.CSharp.Core.targets(75, 5):    at Roslynator.CSharp.Analysis.InvocationExpressionAnalyzer.<>c.<Initialize>b__3_0(SyntaxNodeAnalysisContext f) in /home/sergepavlov/Repro/Analyzers/CSharp/Analysis/InvocationExpressionAnalyzer.cs:line 59
  Microsoft.CSharp.Core.targets(75, 5):    at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
  Microsoft.CSharp.Core.targets(75, 5):    at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
  Microsoft.CSharp.Core.targets(75, 5):    at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
...
```
After that it was a matter of adding another try/catch to the **AvoidBoxingOfValueTypeAnalysis.Analyze** method in question to find out what code pattern caused the analyzer to fail.

```
try
{
    if (!expression.IsKind(SyntaxKind.InterpolatedStringExpression, SyntaxKind.AddExpression)
        && parameters[0].Type.IsObject()
        && context.SemanticModel.GetTypeSymbol(expression, context.CancellationToken)
            .IsValueType)
    {
        DiagnosticHelpers.ReportDiagnostic(context, DiagnosticRules.AvoidBoxingOfValueType, argument);
        return;
    }
}
catch (NullReferenceException)
{
    DiagnosticHelpers.ReportDiagnostic(context, DiagnosticRules.AvoidBoxingOfValueType, argument);
}
```
